site_name: My mini blog
site_url: https://feldmarshxll.github.io/personal-blog/
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

